#!/bin/bash
case "$1" in
    "hci0")
        echo "hci0:	Type: Primary  Bus: USB"
        echo "	UP RUNNING PSCAN"
        ;;
    *)
        echo "hci0:	Type: Primary  Bus: USB"
        echo "	UP RUNNING PSCAN"
        ;;
esac
